### ISSUE TITLE
Can install on my Mac

### ISSUE THREAD

**Issue by jeffreypullin** [fleverest/dirtree-elections#11]
Hi Floyd, 

You mentioning looking at {rater} after my talk on Tuesday prompted me to have a look at {dirtree.elections} last night. 

I was able to install the package onto my (old) MacBook Air and ran some of the README example code. 

I mentioned this to Damjan at our meeting today and he said that you thought that the package didn't work on Mac and that I should let you know that it installed on my machine. So, now you know! :)

Jeffrey

p.s. 
I couldn't run some of the examples in the README: happy to tell you more about that in a separate issue if you want :)

**Comment by fleverest** [comment]
Hi Jeffrey!

Thanks for letting me know, and for taking a look at the project!

Definitely glad to hear it works on _at least some_ macOS installations - not sure why GH actions are complaining yet.

I'll have to update the README, I believe it's just the first command which needs updating. Was it just the initialization `dirtree.irv`? It looks like a typo, and should probably be `dirtree.pirv`. I'll probably push a change in the next hour or so.

Cheers!

**Comment by fleverest** [comment]
I recently merged a change - I would imagine this fixes everything since the test cases pass in GH Actions for macos. I'm going to mark this as resolved :)
