### ISSUE TITLE
count.ballots() is slow

### ISSUE THREAD

**Issue by dvukcevic** [fleverest/dirtree-elections#15]
`count.ballots()` is very slow when there are a large number of ballots.

We should try re-writing it to avoid the `for` loop and the incremental construction of `ballot.counts`.

**Comment by fleverest** [comment]
I've thought a lot about using a (ballot, count) key-value kind of arrangement, and I'm just not sure how I could get it to play nicely. 

In particular we want to be able to shuffle ballots conveniently. Currently we can just call `sample(ballots)`, which I think is very intuitive.

If we went with a ballot-count approach, `sample(ballots)` would essentially be the same as the input. Maybe we could just update the model with ballot-counts of the form `(b, 1)`, but I feel like we lose some elegance there.

Clearly, there are pros and cons for both of the possible interfaces. What do you think we should do?

**Comment by dvukcevic** [comment]
I agree that the current implementation is very intuitive and I like the ability to use `sample(ballots)`.

I don't think we need to change the interface.  I suspect the slowdown is probably caused by the incremental construction of `ballot.counts` on [this line](https://github.com/fleverest/dirtree-elections/blob/76927009e181154c02b7983d7cdfefaa9d13d480/R/pirv_ballots.R#L86):

```
ballot.counts <- c(ballot.counts, list(list(ballot = b, count = 1)))
```

If we can avoid that, and the big `for` loop, for example by vectorising it somehow, then we should get a major speed-up.  (Just like #2)
