### ISSUE TITLE
Need a PIRVBallots constructor

### ISSUE THREAD

**Issue by dvukcevic** [fleverest/dirtree-elections#16]
Sometimes I would like to construct some ballot data 'on the fly' for testing and debugging.  It would be handy to have an easy way to do that, without needing to construct it all by hand (setting attributes, etc.).

**Comment by fleverest** [comment]
I usually use something like the following:
```
structure(
  list(LETTERS[1:5]),
  candidates = LETTERS[1:5],
  class = "PIRVBallots"
)
```
Is that still a little too verbose for testing purposes?

**Comment by dvukcevic** [comment]
Yes, too verbose.  I'd rather write something as simple as:

```{r}
PIRVBallots(list(LETTERS[1:5]))
```
