### ISSUE TITLE
Publish to CRAN

### ISSUE THREAD

**Issue by fleverest** [fleverest/dirtree-elections#19]
We're very close to being able to submit this package to CRAN. We just have a few steps we need to get done first:
- [x] Choose a license for the repository.
- [x] Add some references and acknowledgements to `README.md`.
- [x] Create `NEWS.md` in the home directory. Increment version to 1.0 for an initial release?
- [x] Run a final `R CMD check .` and document the results in `cran-comments.md`.
- [x] Submit using `devtools::release()`.

What do you think @dvukcevic?

**Comment by fleverest** [comment]
I added an MIT license, following in the footsteps of [pbstark/SHANGRLA](https://github.com/pbstark/SHANGRLA/blob/main/LICENSE.md).

**Comment by dvukcevic** [comment]
I think most R packages use the GPL, which is what I would suggest as well.

**Comment by fleverest** [comment]
Fair enough, I changed it to GPL-3

**Comment by dvukcevic** [comment]
Some more suggested tasks:

- [x] Update README, esp. the code examples
- [x] Add installation instructions to the README (initially just for how to install from GitHub)
- [x] Create a package website using [pkgdown](https://pkgdown.r-lib.org/)

**Comment by fleverest** [comment]
It is submitted, and [the status can be monitored here](https://r-hub.github.io/cransays/articles/dashboard.html).

**Comment by fleverest** [comment]
I'm happy we can finally close this Issue - the package can be installed via CRAN! I've just tagged the main branch with the `v1.0.0` release to preserve the current state of the repository, and I've filled in the installation instructions in the readme.
