### ISSUE TITLE
Add CharacterVector of candidate names to RSocialChoiceIRV and read.ballots methods.

### ISSUE THREAD

**Issue by fleverest** [fleverest/dirtree-elections#4]
We should do something like `attr(out, 'candidates') <- LETTERS[1:4]`.

For example, if we calculate social choice on a small subset of the real ballot data, one candidate may be missing. Hence, the elimination order from `social.choice` will be incomplete.

**Comment by dvukcevic** [comment]
Related to this, `read.ballots()` should return a value of class `PIRVBallots`.  Adding the candidates as an attribute will allow this.

**Comment by dvukcevic** [comment]
Here's an example to illustrate a candidate missing from the elimination order.

There are 3 candidates: A, B and C.  Here's a set of 2 ballots that doesn't mention B:

```{r}
> ballots
[[1]]
[1] "C" "A"

[[2]]
[1] "C" "A"

attr(,"class")
[1] "PIRVBallots"
```

Running the social choice function on these does not refer to B:

```{r}
> social.choice.PIRVBallots(ballots)
$elimination_order
[1] "A"

$winners
[1] "C"
```
